cassandra:
  contactPoints:
    - jenova
  validationTimeout: 2 seconds
swagger:
  resourcePackage: examples.resources
videos:
  updateFrequency: 1 hour
  roughDatasetSize: 500000
  bloomFilterFalsePositivePercentage: 0.03

